export const VMS_FETCHED = 'VMS_FETCHED';
export const VMS_FETCHED_SUCCEDDED = 'VMS_FETCHED_SUCCEDDED';
export const VMS_FETCHED_FAILED = 'VMS_FETCHED_FAILED';

export const VM_FETCHED_STATUS = 'VM_FETCHED_STATUS';
export const VM_FETCHED_STATUS_CLOSED = 'VM_FETCHED_STATUS_CLOSED';
export const VM_FETCHED_STATUS_SUCCEDDED = 'VM_FETCHED_STATUS_SUCCEDDED';
export const VM_FETCHED_STATUS_FAILED = 'VM_FETCHED_STATUS_FAILED';

export const VM_DELETED = 'VM_DELETED';
export const VM_DELETED_SUCCEDDED = 'VM_DELETED_SUCCEDDED';
export const VM_DELETED_FAILED = 'VM_DELETED_FAILED';

export const VM_POSTED = 'VM_POSTEDED';
export const VM_POSTED_SUCCEDDED = 'VM_POSTEDED_SUCCEDDED';
export const VM_POSTED_FAILED = 'VM_POSTEDED_FAILED';